services:
    martin.externallinkinnewwindow.listener:
        class: martin\externallinkinnewwindow\event\listener
        arguments:
            - '@config'
            - '@user'
        tags:
            - { name: event.listener }
    martin.externallinkinnewwindow.ucp:
        class: martin\externallinkinnewwindow\event\ucp
        arguments:
            - '@config'
            - '@user'
            - '@request'
            - '@template'
            - '@language'
        tags:
            - { name: event.listener }
